<?php
/**
 *
 */
?>
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
    <ul class="dropdown-menu">
        <li><a href="#">Action</a></li>
        <li><a href="#">Another action</a></li>
        <li><a href="#">Something else here</a></li>
        <li><a href="#">Separated link</a></li>
        <?php echo $this->getChildHtml('top.links') ?>
        <?php echo $this->getChildHtml('store_language') ?>
    </ul>
</li>